### ISSUE TITLE
Function Redis::evaluate() is deprecated 

### ISSUE THREAD

**Issue by DDZH-DEV** [rybakit/phive-queue#24] opened 2021-04-10 03:41 UTC
[2021-04-10T11:28:33+08:00][error] Type: ErrorException; Message: Function Redis::evaluate() is deprecated; File: C:\Users\Zsoner\Desktop\RaxChat\workerman\vendor\rybakit\phive-queue\src\RedisQueue.php; Line: 52;
#0 C:\Users\Zsoner\Desktop\RaxChat\workerman\vendor\rybakit\phive-queue\src\RedisQueue.php(52): log_error(8192, 'Function Redis:...', 'C:\\Users\\Zsoner...', 52, Array)
#1 C:\Users\Zsoner\Desktop\RaxChat\workerman\core\functions.php(412): Phive\Queue\RedisQueue->push('{"from":"100000...')
#2 C:\Users\Zsoner\Desktop\RaxChat\workerman\RaxChat\app\model\Message.php(281): addToQueue('insert_message', Array)
#3 C:\Users\Zsoner\Desktop\RaxChat\workerman\RaxChat\app\service\Joke.php(21):

**Comment by rybakit** [comment] 2021-04-23 14:33
Closing as a duplicate of https://github.com/rybakit/phive-queue/pull/23.

**Closed as completed by rybakit** 2021-04-23 14:33 UTC
